<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Tag extends Model
{
    /**
     * @var mixed
     */

    protected $fillable = ['name', 'slug'];
    /**
     * @var mixed
     */


    public function posts()
    {
        return $this->belongsToMany(Post::class, 'post_tags');
    }

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = empty($value) ?
            Str::slug($this->attributes['name'])
            : str_replace(' ', '-', $value);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function ($model) {
            $model->slug .= $model->id;
            $model->save();
        });
    }
}
